project:
  type: website

website:
  title: ""
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Service
        href: service.qmd
      - text: Writing
        href: writing/index.qmd
      - text: CV
        href: "#"

format:
  html:
    css: styles.css
